# Atividade 1 — Exercícios com os comandos básicos de pandas para EDA


Responda as perguntas abaixo no notebook (cada resposta deve ter ao menos uma célula de código que produza o output e, logo abaixo, uma célula de texto com a sua interpretação).

## 1) Carregue o dataset e mostre as primeiras 10 linhas.

In [ ]:
import pandas as pd
df = pd.read_csv('emendas.csv')
df.head(10)

/tmp/ipykernel_2038/543231991.py:2: DtypeWarning: Columns (0,3,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('emendas.csv')

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
0,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,ALVORADA - RS,4300604,ALVORADA,4300000,...,1D73,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0000,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,"700000,00","0,00","0,00","0,00","690900,00","9100,00"
1,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,SANTA ISABEL DO PARÁ - PA,1506500,SANTA ISABEL DO PARÁ,1500000,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0000,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"487500,00","0,00","0,00","0,00","487500,00","0,00"
2,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,BARRA BONITA - SC,4202099,BARRA BONITA,4200000,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0000,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"100000,00","0,00","0,00","0,00","0,00","100000,00"
3,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,ARARAQUARA - SP,3503208,ARARAQUARA,3500000,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0000,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"243750,00","0,00","0,00","0,00","243750,00","0,00"
4,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CAMPO LARGO - PR,4104204,CAMPO LARGO,4100000,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0000,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"1658333,94","0,00","0,00","0,00","527200,00","1131133,94"
5,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CAMPINAS DO SUL - RS,4303806,CAMPINAS DO SUL,4300000,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0000,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"243750,00","0,00","0,00","0,00","0,00","243750,00"
6,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,MORENO - PE,2609402,MORENO,2600000,...,20RP,APOIO A INFRAESTRUTURA PARA A EDUCACAO BASICA,0000,INFRAESTRUTURA PARA A EDUCACAO BASICA - DESPES...,"700000,00","0,00","0,00","0,00","700000,00","0,00"
7,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,NOVA FLORESTA - PB,2510105,NOVA FLORESTA,2500000,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0000,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"278700,00","0,00","0,00","0,00","0,00","278700,00"
8,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,SANTIAGO DO SUL - SC,4215695,SANTIAGO DO SUL,4200000,...,20ZV,FOMENTO AO SETOR AGROPECUARIO,0000,FOMENTO AO SETOR AGROPECUARIO - DESPESAS DIVERSAS,"300000,00","300000,00","300000,00","0,00","0,00","0,00"
9,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CIANORTE - PR,4105508,CIANORTE,4100000,...,1D73,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0000,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,"245850,00","0,00","0,00","0,00","0,00","245850,00"

Eu observo as dez primeiras linhas do dataframe contendo informações sobre uma emenda, suas finalidades, valores, onde foi implementada e etc.

## 2) Quantas linhas e colunas o dataset possui?

In [ ]:
df.shape

(86589, 28)

Esses números significam, respectivamente, a quantidade de linhas e colunas que o DataFrame possui.

## 3) Liste os nomes das colunas e descreva brevemente o que você entende que cada coluna representa.

In [ ]:
df.columns

Index(['Código da Emenda', 'Ano da Emenda', 'Tipo de Emenda',
       'Código do Autor da Emenda', 'Nome do Autor da Emenda',
       'Número da emenda', 'Localidade de aplicação do recurso',
       'Código Município IBGE', 'Município', 'Código UF IBGE', 'UF', 'Região',
       'Código Função', 'Nome Função', 'Código Subfunção', 'Nome Subfunção',
       'Código Programa', 'Nome Programa', 'Código Ação', 'Nome Ação',
       'Código Plano Orçamentário', 'Nome Plano Orçamentário',
       'Valor Empenhado', 'Valor Liquidado', 'Valor Pago',
       'Valor Restos A Pagar Inscritos', 'Valor Restos A Pagar Cancelados',
       'Valor Restos A Pagar Pagos'],
      dtype='object')

Código da Emenda: Identificador único da emenda.
Ano da Emenda: Ano de registro da emenda.
Tipo de Emenda: Categoria da emenda (individual, bancada, etc.).
Código do Autor da Emenda: Identificador do autor.
Nome do Autor da Emenda: Nome do parlamentar autor.
Número da Emenda: Número oficial da emenda.
Localidade de aplicação do recurso: Onde o recurso será aplicado.
Código Município IBGE: Código oficial do município (IBGE).
Município: Nome da cidade.
Código UF IBGE: Código oficial do estado (IBGE).
UF: Sigla do estado.
Região: Região do país.
Código Função: Código da área principal do gasto.
Nome Função: Nome da área (ex: saúde, educação).
Código Subfunção: Código da subárea.
Nome Subfunção: Nome da subárea.
Código Programa: Código do programa de governo.
Nome Programa: Nome do programa.
Código Ação: Código da ação.
Nome Ação: Nome da ação.
Código Plano Orçamentário: Código detalhado da aplicação.
Nome Plano Orçamentário: Nome do plano orçamentário.
Valor Empenhado: Valor reservado para o gasto.
Valor Liquidado: Valor já confirmado após execução.
Valor Pago: Valor efetivamente pago.
Valor Restos a Pagar Inscritos: Valores não pagos no ano e transferidos.
Valor Restos a Pagar Cancelados: Valores que foram cancelados.
Valor Restos a Pagar Pagos: Valores pagos posteriormente.

## 4) Existem valores nulos? quantos?

In [ ]:
nulos = df.isnull().sum()
print(nulos)

Código da Emenda                      0
Ano da Emenda                         0
Tipo de Emenda                        0
Código do Autor da Emenda             0
Nome do Autor da Emenda               0
Número da emenda                      0
Localidade de aplicação do recurso    0
Código Município IBGE                 0
Município                             0
Código UF IBGE                        0
UF                                    0
Região                                0
Código Função                         0
Nome Função                           0
Código Subfunção                      0
Nome Subfunção                        0
Código Programa                       0
Nome Programa                         0
Código Ação                           0
Nome Ação                             0
Código Plano Orçamentário             1
Nome Plano Orçamentário               1
Valor Empenhado                       1
Valor Liquidado                       1
Valor Pago                            1
Valor Restos A Pagar Inscritos        1
Valor Restos A Pagar Cancelados       1
Valor Restos A Pagar Pagos            1
dtype: int64

Sim, existem 8 valores nulos.

## 5) Mostre os tipos das variáveis (se int, string, boolean, float...) e analise se alguma variável parece ter o tipo errado. Faça isso da maneira mais objetiva e otimizada possível.

In [ ]:
df.dtypes

Código da Emenda                      object
Ano da Emenda                          int64
Tipo de Emenda                        object
Código do Autor da Emenda             object
Nome do Autor da Emenda               object
Número da emenda                      object
Localidade de aplicação do recurso    object
Código Município IBGE                 object
Município                             object
Código UF IBGE                         int64
UF                                    object
Região                                object
Código Função                         object
Nome Função                           object
Código Subfunção                      object
Nome Subfunção                        object
Código Programa                       object
Nome Programa                         object
Código Ação                           object
Nome Ação                             object
Código Plano Orçamentário             object
Nome Plano Orçamentário               object
Valor Empenhado                       object
Valor Liquidado                       object
Valor Pago                            object
Valor Restos A Pagar Inscritos        object
Valor Restos A Pagar Cancelados       object
Valor Restos A Pagar Pagos            object
dtype: object

Todos os códigos ficariam mais otimizados caso fossem inteiros, e todos os valores ficariam melhores como float.

## 6) Usando a coluna `Ano da Emenda` como base, descubra até que ano o dataset está atualizado (mostre as 8 primeiras linhas do df ordenado desc).

In [ ]:
df.sort_values(by='Ano da Emenda', ascending=False).head(8)

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
86567,202544200001,2025,Emenda Individual - Transferências com Finalid...,4420,MARCOS POLLON,1,MÚLTIPLO,Sem informação,Múltiplo,5000000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,"12291368,00","11141368,00","11141368,00","0,00","0,00","0,00"
86581,202537240006,2025,Emenda Individual - Transferências com Finalid...,3724,MARCOS SOARES,6,RIO DE JANEIRO (UF),Sem informação,Sem informação,3300000,...,20JP,DESENVOLVIMENTO DE ATIVIDADES E APOIO A PROGRA...,0000,DESENVOLVIMENTO DE ATIVIDADES E APOIO A PROGRA...,"2480000,00","20000,00","20000,00","0,00","0,00","0,00"
86558,202592040006,2025,Emenda Individual - Transferências com Finalid...,9204,MARCOS DO VAL,6,ESPÍRITO SANTO (UF),Sem informação,Sem informação,3200000,...,21EO,APOIO AO SISTEMA PENITENCIARIO NACIONAL,0000,APOIO AO SISTEMA PENITENCIARIO NACIONAL,"1400000,00","0,00","0,00","0,00","0,00","0,00"
86559,202592040007,2025,Emenda Individual - Transferências Especiais,9204,MARCOS DO VAL,7,MÚLTIPLO,Sem informação,Múltiplo,3200000,...,0EC2,TRANSFERENCIAS ESPECIAIS,0000,TRANSFERENCIAS ESPECIAIS,"9739714,85","9642317,85","9642317,85","0,00","0,00","0,00"
86560,202592040008,2025,Emenda Individual - Transferências com Finalid...,9204,MARCOS DO VAL,8,MÚLTIPLO,Sem informação,Múltiplo,3200000,...,20JP,DESENVOLVIMENTO DE ATIVIDADES E APOIO A PROGRA...,0000,DESENVOLVIMENTO DE ATIVIDADES E APOIO A PROGRA...,"500000,00","10000,00","0,00","0,00","0,00","0,00"
86561,202592040009,2025,Emenda Individual - Transferências com Finalid...,9204,MARCOS DO VAL,9,MÚLTIPLO,Sem informação,Múltiplo,3200000,...,219G,ESTRUTURACAO DA REDE DE SERVICOS E FORTALECIME...,0000,ESTRUTURACAO DA REDE DE SERVICOS E FORTALECIME...,"900000,00","400000,00","400000,00","0,00","0,00","0,00"
86562,202541610001,2025,Emenda Individual - Transferências com Finalid...,4161,MARCOS PEREIRA,1,MÚLTIPLO,Sem informação,Múltiplo,3500000,...,2E90,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,"8637993,00","8637993,00","8637993,00","0,00","0,00","0,00"
86563,202541610002,2025,Emenda Individual - Transferências com Finalid...,4161,MARCOS PEREIRA,2,MÚLTIPLO,Sem informação,Múltiplo,3500000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,"5000000,00","5000000,00","5000000,00","0,00","0,00","0,00"

O ano mais recente presente no dataset é 2025, pois estamos pedindo para o código pegar do maior ano até o menor.

## 7) execute um  `describe()` e explique uma conclusão simples que você consegue tirar a partir das estatísticas (se algumas colunas deveriam aparecer no describe mas não aparecem, indique o motivo que você acredita que esteja causando esse problema).

In [ ]:
df.describe()

       Ano da Emenda  Código UF IBGE
count   86589.000000    8.658900e+04
mean     2019.019633    2.946591e+06
std         3.329069    1.262527e+06
min      2014.000000   -1.400000e+01
25%      2016.000000    2.300000e+06
50%      2019.000000    3.100000e+06
75%      2022.000000    3.500000e+06
max      2025.000000    5.300000e+06

Apenas aparecem as colunas que foram identificadas como int64, sendo analisadas como números e podendo serem processadas em operações matemáticas, já as outras não foram, mesmo as que também possuem números como informação.

## 8) Mostre as últimas 5 linhas do dataset e escreva se a última linha parece completa (sem muitos nulos) ou não.

In [ ]:
df.tail(5)

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
86584,202544210003,2025,Emenda Individual - Transferências com Finalid...,4421,MARCOS TAVARES,3,PIRAÍ - RJ,3304003,PIRAÍ,3300000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,"1000000,00","1000000,00","1000000,00","0,00","0,00","0,00"
86585,202544220001,2025,Emenda Individual - Transferências com Finalid...,4422,MARIA ARRAES,1,MÚLTIPLO,Sem informação,Múltiplo,2600000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,"20378000,00","18638000,00","18638000,00","0,00","0,00","0,00"
86586,202544220002,2025,Emenda Individual - Transferências Especiais,4422,MARIA ARRAES,2,MÚLTIPLO,Sem informação,Múltiplo,2600000,...,0EC2,TRANSFERENCIAS ESPECIAIS,0000,TRANSFERENCIAS ESPECIAIS,"1930500,00","1930500,00","1930500,00","0,00","0,00","0,00"
86587,202544220003,2025,Emenda Individual - Transferências Especiais,4422,MARIA ARRAES,3,MÚLTIPLO,Sem informação,Múltiplo,2600000,...,0EC2,TRANSFERENCIAS ESPECIAIS,0000,TRANSFERENCIAS ESPECIAIS,"11437984,15","11323605,15","11323605,15","0,00","0,00","0,00"
86588,202544220004,2025,Emenda Individual - Transferências com Finalid...,4422,MARIA ARRAES,4,PERNAMBUCO (UF),Sem informação,Sem informação,2600000,...,21GG,APOIO AS INICIATIVAS DE PROMOCAO DA IGUALDADE ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Tem 8 informações nulas, tornando a linha difícil de analisar.

## 9) existem valores duplicados no dataframe? Caso positivo, quantos?

In [ ]:
df.duplicated().sum()

np.int64(0)

Não existem valores duplicados no dataframe.